name: flutter_ecommerce_app
description: A new Flutter project discover project.
publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: any
  cupertino_icons: ^0.1.3
  google_fonts: ^1.1.0
  font_awesome_flutter: any
  carousel_slider:
  intl:
  slugify:
  shared_preferences:
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
